# ==============================================================================
# Copyright (C) 2025 2noScript
#
# This project is licensed under the Apache License 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
#                       ,-,-
#                      / / |
#    ,-'             _/ / /
#   (-_          _,-' `Z_/
#    "#:      ,-'_,-.    \  _
#     #'    _(_-'_()\     \" |
#   ,--_,--'                 |
#  / ""                      L-'\
#  \,--^---v--v-._        /   \ |
#    \_________________,-'      |
#                     \          \
#                      \          \
#   Feed me Stars ⭐    \          \
# ==============================================================================


PromeaiTags = [
    # {
    #     "name": "All",
    #     "value": "",
    #     "subtags": [
    #         {"name": "Architecture", "value": "architecture"},
    #         {"name": "3d rendering", "value": "3d-rendering"},
    #         {"name": "Modern architecture", "value": "modern-architecture"},
    #         {"name": "Girl", "value": "girl"},
    #         {"name": "Interior", "value": "interior"},
    #         {"name": "Floorplan home", "value": "floorplan-home"},
    #         {"name": "Logo", "value": "logo"},
    #         {"name": "Woman", "value": "woman"},
    #         {"name": "Man", "value": "man"},
    #         {"name": "Anime", "value": "anime"},
    #         {"name": "Floor plan", "value": "floor-plan"},
    #         {"name": "Landscape plan", "value": "landscape-plan"},
    #         {"name": "Sketch", "value": "sketch"},
    #         {"name": "Schoolgirl", "value": "schoolgirl"},
    #         {"name": "Modern house", "value": "modern-house"},
    #         {"name": "Fantasy portrait", "value": "fantasy-portrait"},
    #         {"name": "Professional", "value": "professional"},
    #         {"name": "School", "value": "school"},
    #         {"name": "Cartoon", "value": "cartoon"},
    #         {"name": "Kitchen", "value": "kitchen"},
    #         {"name": "Couple", "value": "couple"},
    #         {"name": "House floorplan", "value": "house-floorplan"},
    #         {"name": "Boy", "value": "boy"},
    #         {"name": "Plan", "value": "plan"},
    #         {"name": "House", "value": "house"},
    #         {"name": "Bedroom", "value": "bedroom"},
    #         {"name": "Teen", "value": "teen"},
    #         {"name": "Office", "value": "office"},
    #         {"name": "Car", "value": "car"},
    #         {"name": "Business", "value": "business"},
    #     ],
    # },
    {
        "name": "Sketch Rendering",
        "value": "promeai",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "Interior", "value": "interior"},
            {"name": "Commercial space", "value": "commercial-space"},
            {"name": "Landscape design", "value": "landscape-design"},
            {"name": "Game character", "value": "game-character"},
            {"name": "Game scene", "value": "game-scene"},
            {"name": "Fashion design", "value": "fashion-design"},
            {"name": "Furniture design", "value": "furniture-design"},
            {"name": "Jewelry design", "value": "jewelry-design"},
            {"name": "Footwear design", "value": "footwear-design"},
            {"name": "Vehicle design", "value": "vehicle-design"},
            {"name": "Consumer electronics", "value": "consumer-electronics"},
            {"name": "Packaging design", "value": "packaging-design"},
            {"name": "Modern architecture", "value": "modern-architecture"},
            {"name": "Anime", "value": "anime"},
            {"name": "Floorplan home", "value": "floorplan-home"},
            {"name": "Sketch", "value": "sketch"},
            {"name": "Landscape plan", "value": "landscape-plan"},
            {"name": "Floor plan", "value": "floor-plan"},
            {"name": "Fantasy portrait", "value": "fantasy-portrait"},
        ],
    },
    {
        "name": "AI Image Generator",
        "value": "textToRenderImage",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "Interior", "value": "interior"},
            {"name": "Girl", "value": "girl"},
            {"name": "3d rendering", "value": "3d-rendering"},
            {"name": "Logo", "value": "logo"},
            {"name": "Modern architecture", "value": "modern-architecture"},
            {"name": "Anime", "value": "anime"},
            {"name": "Woman", "value": "woman"},
            {"name": "It", "value": "it"},
            {"name": "Floorplan home", "value": "floorplan-home"},
            {"name": "Man", "value": "man"},
            {"name": "Sketch", "value": "sketch"},
            {"name": "Couple", "value": "couple"},
            {"name": "School", "value": "school"},
            {"name": "Modern house", "value": "modern-house"},
            {"name": "Floor plan", "value": "floor-plan"},
            {"name": "Landscape plan", "value": "landscape-plan"},
            {"name": "Fantasy portrait", "value": "fantasy-portrait"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Boy", "value": "boy"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Office", "value": "office"},
            {"name": "House floorplan", "value": "house-floorplan"},
            {"name": "House", "value": "house"},
            {"name": "Bedroom", "value": "bedroom"},
            {"name": "Car", "value": "car"},
            {"name": "Professional", "value": "professional"},
            {"name": "Teen", "value": "teen"},
            {"name": "Plan", "value": "plan"},
            {"name": "Schoolgirl", "value": "schoolgirl"},
        ],
    },
    {
        "name": "Creative Fusion",
        "value": "compositeRenderImage",
        "subtags": [
            {"name": "Female", "value": "female"},
            {"name": "Male", "value": "male"},
            {"name": "Children", "value": "children"},
            {"name": "Animals", "value": "animals"},
            {"name": "Landscape architecture", "value": "landscape-architecture"},
            {"name": "Hand-painted", "value": "hand-painted"},
            {"name": "Interior design", "value": "interior-design"},
            {"name": "Commercial space", "value": "commercial-space"},
            {"name": "Product design", "value": "product-design"},
            {"name": "Fashion design", "value": "fashion-design"},
            {"name": "C4D", "value": "c4d"},
            {"name": "Papercutting", "value": "papercutting"},
            {"name": "Fantasy portrait", "value": "fantasy-portrait"},
            {"name": "House", "value": "house"},
            {"name": "Girl", "value": "girl"},
            {"name": "Woman", "value": "woman"},
            {"name": "Office", "value": "office"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Boy", "value": "boy"},
            {"name": "Car", "value": "car"},
        ],
    },
    {
        "name": "Text to Video",
        "value": "textToVideo",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "Girl", "value": "girl"},
            {"name": "Anime", "value": "anime"},
            {"name": "Woman", "value": "woman"},
            {"name": "Interior", "value": "interior"},
            {"name": "Man", "value": "man"},
            {"name": "It", "value": "it"},
            {"name": "Couple", "value": "couple"},
            {"name": "School", "value": "school"},
            {"name": "Modern house", "value": "modern-house"},
            {"name": "Fantasy portrait", "value": "fantasy-portrait"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Boy", "value": "boy"},
            {"name": "Car", "value": "car"},
            {"name": "Female", "value": "female"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Office", "value": "office"},
            {"name": "House", "value": "house"},
            {"name": "Bedroom", "value": "bedroom"},
            {"name": "Professional", "value": "professional"},
        ],
    },
    {
        "name": "Image to Video",
        "value": "imageToVideo",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "Girl", "value": "girl"},
            {"name": "3d rendering", "value": "3d-rendering"},
            {"name": "Logo", "value": "logo"},
            {"name": "Modern architecture", "value": "modern-architecture"},
            {"name": "Woman", "value": "woman"},
            {"name": "Interior", "value": "interior"},
            {"name": "Man", "value": "man"},
            {"name": "Couple", "value": "couple"},
            {"name": "School", "value": "school"},
            {"name": "Modern house", "value": "modern-house"},
            {"name": "Fantasy portrait", "value": "fantasy-portrait"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Boy", "value": "boy"},
            {"name": "Female", "value": "female"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Office", "value": "office"},
            {"name": "House", "value": "house"},
            {"name": "Car", "value": "car"},
            {"name": "Anime", "value": "anime"},
        ],
    },
    {
        "name": "Photo to Sketch",
        "value": "photoToSketch",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "Modern architecture", "value": "modern-architecture"},
            {"name": "3d rendering", "value": "3d-rendering"},
            {"name": "Interior", "value": "interior"},
            {"name": "Man", "value": "man"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Girl", "value": "girl"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Portrait", "value": "portrait"},
            {"name": "House", "value": "house"},
            {"name": "Home", "value": "home"},
            {"name": "Car", "value": "car"},
            {"name": "Landscape design", "value": "landscape-design"},
            {"name": "Furniture", "value": "furniture"},
            {"name": "Game", "value": "game"},
            {"name": "Floor", "value": "floor"},
            {"name": "Bedroom", "value": "bedroom"},
            {"name": "Boy", "value": "boy"},
            {"name": "Beauty", "value": "beauty"},
            {"name": "Loft", "value": "loft"},
        ],
    },
    {
        "name": "HD Upscaler",
        "value": "tileUpscale",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "Girl", "value": "girl"},
            {"name": "3d rendering", "value": "3d-rendering"},
            {"name": "Logo", "value": "logo"},
            {"name": "Modern architecture", "value": "modern-architecture"},
            {"name": "Woman", "value": "woman"},
            {"name": "Interior", "value": "interior"},
            {"name": "Man", "value": "man"},
            {"name": "Couple", "value": "couple"},
            {"name": "School", "value": "school"},
            {"name": "Modern house", "value": "modern-house"},
            {"name": "Fantasy portrait", "value": "fantasy-portrait"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Boy", "value": "boy"},
            {"name": "Female", "value": "female"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Office", "value": "office"},
            {"name": "House", "value": "house"},
            {"name": "Car", "value": "car"},
            {"name": "Anime", "value": "anime"},
            {"name": "Portrait", "value": "portrait"},
            {"name": "Home", "value": "home"},
            {"name": "Landscape design", "value": "landscape-design"},
            {"name": "Furniture", "value": "furniture"},
            {"name": "Game", "value": "game"},
            {"name": "Floor", "value": "floor"},
            {"name": "Bedroom", "value": "bedroom"},
            {"name": "Beauty", "value": "beauty"},
            {"name": "Loft", "value": "loft"},
            {"name": "Design", "value": "design"},
            {"name": "Landscape", "value": "landscape"},
            {"name": "Building", "value": "building"},
            {"name": "Male", "value": "male"},
        ],
    },
    {
        "name": "Image Variation",
        "value": "variation",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "Girl", "value": "girl"},
            {"name": "3d rendering", "value": "3d-rendering"},
            {"name": "Logo", "value": "logo"},
            {"name": "Modern architecture", "value": "modern-architecture"},
            {"name": "Woman", "value": "woman"},
            {"name": "Interior", "value": "interior"},
            {"name": "Man", "value": "man"},
            {"name": "Couple", "value": "couple"},
            {"name": "School", "value": "school"},
            {"name": "Modern house", "value": "modern-house"},
            {"name": "Fantasy portrait", "value": "fantasy-portrait"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Boy", "value": "boy"},
            {"name": "Female", "value": "female"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Office", "value": "office"},
            {"name": "House", "value": "house"},
            {"name": "Car", "value": "car"},
            {"name": "Anime", "value": "anime"},
            {"name": "Portrait", "value": "portrait"},
            {"name": "Home", "value": "home"},
            {"name": "Landscape design", "value": "landscape-design"},
            {"name": "Furniture", "value": "furniture"},
            {"name": "Game", "value": "game"},
            {"name": "Floor", "value": "floor"},
            {"name": "Bedroom", "value": "bedroom"},
            {"name": "Beauty", "value": "beauty"},
            {"name": "Loft", "value": "loft"},
        ],
    },
    {
        "name": "Text Effects",
        "value": "textRender",
        "subtags": [
            {"name": "Realistic", "value": "realistic"},
            {"name": "Foods", "value": "foods"},
            {"name": "Pirozhki", "value": "pirozhki"},
            {"name": "Popsicles", "value": "popsicles"},
            {"name": "Ice cream", "value": "ice-cream"},
            {"name": "Cantaloupe", "value": "cantaloupe"},
            {"name": "Calligraphy", "value": "calligraphy"},
            {"name": "Light", "value": "light"},
            {"name": "Shadow", "value": "shadow"},
            {"name": "Illustration", "value": "illustration"},
            {"name": "Sky", "value": "sky"},
            {"name": "Painting", "value": "painting"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Fantasy", "value": "fantasy"},
            {"name": "Landscape", "value": "landscape"},
            {"name": "City", "value": "city"},
            {"name": "Autumn", "value": "autumn"},
            {"name": "Stone", "value": "stone"},
            {"name": "Wood", "value": "wood"},
            {"name": "Glass", "value": "glass"},
        ],
    },
    {
        "name": "Outpainting",
        "value": "sizeExpansion",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "Girl", "value": "girl"},
            {"name": "3d rendering", "value": "3d-rendering"},
            {"name": "Woman", "value": "woman"},
            {"name": "Man", "value": "man"},
            {"name": "Logo", "value": "logo"},
            {"name": "Modern architecture", "value": "modern-architecture"},
            {"name": "Anime", "value": "anime"},
            {"name": "Fantasy portrait", "value": "fantasy-portrait"},
            {"name": "Interior", "value": "interior"},
            {"name": "Light", "value": "light"},
            {"name": "House", "value": "house"},
            {"name": "Couple", "value": "couple"},
            {"name": "School", "value": "school"},
            {"name": "Modern house", "value": "modern-house"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Office", "value": "office"},
            {"name": "Boy", "value": "boy"},
            {"name": "Car", "value": "car"},
        ],
    },
    {
        "name": "Erase & Replace",
        "value": "eraseReplace",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "Girl", "value": "girl"},
            {"name": "3d rendering", "value": "3d-rendering"},
            {"name": "Modern architecture", "value": "modern-architecture"},
            {"name": "Woman", "value": "woman"},
            {"name": "Interior", "value": "interior"},
            {"name": "Floorplan home", "value": "floorplan-home"},
            {"name": "Man", "value": "man"},
            {"name": "Couple", "value": "couple"},
            {"name": "School", "value": "school"},
            {"name": "Modern house", "value": "modern-house"},
            {"name": "Fantasy portrait", "value": "fantasy-portrait"},
            {"name": "House", "value": "house"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Boy", "value": "boy"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Office", "value": "office"},
            {"name": "House floorplan", "value": "house-floorplan"},
            {"name": "Bedroom", "value": "bedroom"},
            {"name": "Car", "value": "car"},
        ],
    },
    {
        "name": "AI Supermodel",
        "value": "supermodel",
        "subtags": [
            {"name": "Girl", "value": "girl"},
            {"name": "Female", "value": "female"},
            {"name": "Male", "value": "male"},
            {"name": "Asians", "value": "asians"},
            {"name": "Europeans", "value": "europeans"},
            {"name": "Eastern Europeans", "value": "eastern-europeans"},
            {"name": "Africans", "value": "africans"},
            {"name": "Indians", "value": "indians"},
            {"name": "Straight hair", "value": "straight-hair"},
            {"name": "Young", "value": "young"},
            {"name": "M", "value": "m"},
            {"name": "Smile", "value": "smile"},
            {"name": "Underwear", "value": "underwear"},
            {"name": "Dress", "value": "dress"},
            {"name": "White", "value": "white"},
            {"name": "Pink", "value": "pink"},
            {"name": "Coat", "value": "coat"},
            {"name": "Jewelry", "value": "jewelry"},
            {"name": "Women", "value": "women"},
            {"name": "Man", "value": "man"},
        ],
    },
    {
        "name": "AI Background Generator",
        "value": "outPaint",
        "subtags": [
            {"name": "Furniture", "value": "furniture"},
            {"name": "Interior", "value": "interior"},
            {"name": "Bottle", "value": "bottle"},
            {"name": "Cream", "value": "cream"},
            {"name": "Product", "value": "product"},
            {"name": "Decor", "value": "decor"},
            {"name": "Table", "value": "table"},
            {"name": "Room", "value": "room"},
            {"name": "Light", "value": "light"},
            {"name": "Oil", "value": "oil"},
            {"name": "Water", "value": "water"},
            {"name": "Necklace", "value": "necklace"},
            {"name": "Living room", "value": "living-room"},
            {"name": "Perfume", "value": "perfume"},
            {"name": "Landscape", "value": "landscape"},
            {"name": "Tree", "value": "tree"},
            {"name": "Shoes", "value": "shoes"},
            {"name": "Glass", "value": "glass"},
            {"name": "Portrait", "value": "portrait"},
            {"name": "Office", "value": "office"},
        ],
    },
    {
        "name": "Background Remover",
        "value": "matting",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "3d rendering", "value": "3d-rendering"},
            {"name": "Modern architecture", "value": "modern-architecture"},
            {"name": "Girl", "value": "girl"},
            {"name": "Interior", "value": "interior"},
            {"name": "Floorplan home", "value": "floorplan-home"},
            {"name": "Logo", "value": "logo"},
            {"name": "Woman", "value": "woman"},
            {"name": "Man", "value": "man"},
            {"name": "Anime", "value": "anime"},
            {"name": "Floor plan", "value": "floor-plan"},
            {"name": "Landscape plan", "value": "landscape-plan"},
            {"name": "Sketch", "value": "sketch"},
            {"name": "Schoolgirl", "value": "schoolgirl"},
            {"name": "Modern house", "value": "modern-house"},
            {"name": "Fantasy portrait", "value": "fantasy-portrait"},
            {"name": "Professional", "value": "professional"},
            {"name": "School", "value": "school"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Couple", "value": "couple"},
            {"name": "House floorplan", "value": "house-floorplan"},
            {"name": "Boy", "value": "boy"},
            {"name": "Plan", "value": "plan"},
            {"name": "House", "value": "house"},
            {"name": "Bedroom", "value": "bedroom"},
            {"name": "Teen", "value": "teen"},
            {"name": "Office", "value": "office"},
            {"name": "Car", "value": "car"},
            {"name": "Business", "value": "business"},
        ],
    },
    {
        "name": "AI PNG Generator",
        "value": "textToPngImage",
        "subtags": [
            {"name": "Tree", "value": "tree"},
            {"name": "Arrow", "value": "arrow"},
            {"name": "Fire", "value": "fire"},
            {"name": "Flower", "value": "flower"},
            {"name": "Heart", "value": "heart"},
            {"name": "Crown", "value": "crown"},
            {"name": "Explosion", "value": "explosion"},
            {"name": "Circle", "value": "circle"},
            {"name": "Smoke", "value": "smoke"},
            {"name": "Sun", "value": "sun"},
            {"name": "Firework", "value": "firework"},
            {"name": "Bubble", "value": "bubble"},
            {"name": "Cloud", "value": "cloud"},
            {"name": "Butterfly", "value": "butterfly"},
            {"name": "Weed", "value": "weed"},
            {"name": "Snow", "value": "snow"},
            {"name": "Flame", "value": "flame"},
            {"name": "Star", "value": "star"},
            {"name": "Sparkle", "value": "sparkle"},
            {"name": "Moon", "value": "moon"},
            {"name": "Leaf", "value": "leaf"},
            {"name": "Football", "value": "football"},
            {"name": "Lightning", "value": "lightning"},
            {"name": "Car", "value": "car"},
            {"name": "Fish", "value": "fish"},
            {"name": "Light", "value": "light"},
            {"name": "Building", "value": "building"},
            {"name": "Furniture", "value": "furniture"},
            {"name": "Money", "value": "money"},
            {"name": "Snowflake", "value": "snowflake"},
        ],
    },
    {
        "name": "AI Logo Generator",
        "value": "textToLogoImage",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "3d rendering", "value": "3d rendering"},
            {"name": "Modern architecture", "value": "modern architecture"},
            {"name": "Girl", "value": "girl"},
            {"name": "Interior", "value": "interior"},
            {"name": "Floorplan home", "value": "floorplan home"},
            {"name": "Logo", "value": "logo"},
            {"name": "Woman", "value": "woman"},
            {"name": "Man", "value": "man"},
            {"name": "Anime", "value": "anime"},
            {"name": "Floor plan", "value": "floor plan"},
            {"name": "Landscape plan", "value": "landscape plan"},
            {"name": "Sketch", "value": "sketch"},
            {"name": "Schoolgirl", "value": "schoolgirl"},
            {"name": "Modern house", "value": "modern house"},
            {"name": "Fantasy portrait", "value": "fantasy portrait"},
            {"name": "Professional", "value": "professional"},
            {"name": "School", "value": "school"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Couple", "value": "couple"},
            {"name": "House floorplan", "value": "house floorplan"},
            {"name": "Boy", "value": "boy"},
            {"name": "Plan", "value": "plan"},
            {"name": "House", "value": "house"},
            {"name": "Bedroom", "value": "bedroom"},
            {"name": "Teen", "value": "teen"},
            {"name": "Office", "value": "office"},
            {"name": "Car", "value": "car"},
            {"name": "Business", "value": "business"},
        ],
    },
    {
        "name": "Pattern Generator",
        "value": "continuousImageByText",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "3d rendering", "value": "3d rendering"},
            {"name": "Modern architecture", "value": "modern architecture"},
            {"name": "Girl", "value": "girl"},
            {"name": "Interior", "value": "interior"},
            {"name": "Floorplan home", "value": "floorplan home"},
            {"name": "Logo", "value": "logo"},
            {"name": "Woman", "value": "woman"},
            {"name": "Man", "value": "man"},
            {"name": "Anime", "value": "anime"},
            {"name": "Floor plan", "value": "floor plan"},
            {"name": "Landscape plan", "value": "landscape plan"},
            {"name": "Sketch", "value": "sketch"},
            {"name": "Schoolgirl", "value": "schoolgirl"},
            {"name": "Modern house", "value": "modern house"},
            {"name": "Fantasy portrait", "value": "fantasy portrait"},
            {"name": "Professional", "value": "professional"},
            {"name": "School", "value": "school"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Couple", "value": "couple"},
            {"name": "House floorplan", "value": "house floorplan"},
            {"name": "Boy", "value": "boy"},
            {"name": "Plan", "value": "plan"},
            {"name": "House", "value": "house"},
            {"name": "Bedroom", "value": "bedroom"},
            {"name": "Teen", "value": "teen"},
            {"name": "Office", "value": "office"},
            {"name": "Car", "value": "car"},
            {"name": "Business", "value": "business"},
        ],
    },
    {
        "name": "Exterior Renovator",
        "value": "aiExteriorRenovate",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "Building", "value": "building"},
            {"name": "Apartment", "value": "apartment"},
            {"name": "House", "value": "house"},
            {"name": "Exterior", "value": "exterior"},
            {"name": "Villa", "value": "villa"},
            {"name": "Minimalism", "value": "minimalism"},
            {"name": "Modern architecture", "value": "modern architecture"},
            {"name": "Apartment complex", "value": "apartment complex"},
            {"name": "Shed", "value": "shed"},
            {"name": "School", "value": "school"},
            {"name": "Modern house", "value": "modern house"},
            {"name": "Home", "value": "home"},
            {"name": "Brutalist architecture", "value": "brutalist architecture"},
            {"name": "Gothic architecture", "value": "gothic architecture"},
            {"name": "Architectural", "value": "architectural"},
            {"name": "Architectural design", "value": "architectural design"},
            {"name": "Landscape architecture", "value": "landscape architecture"},
            {"name": "Architectural shingles", "value": "architectural shingles"},
            {"name": "Apartment buildings", "value": "apartment buildings"},
            {"name": "Steel buildings", "value": "steel buildings"},
        ],
    },
    {
        "name": "Anime PFP Generator",
        "value": "aiAnimeHeadshot",
        "subtags": [
            {"name": "Girl", "value": "girl"},
            {"name": "Woman", "value": "woman"},
            {"name": "Man", "value": "man"},
            {"name": "Anime", "value": "anime"},
            {"name": "Fantasy portrait", "value": "fantasy portrait"},
            {"name": "School", "value": "school"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Boy", "value": "boy"},
            {"name": "Business", "value": "business"},
            {"name": "Professional", "value": "professional"},
            {"name": "Headshot", "value": "headshot"},
            {"name": "Sexy girl", "value": "sexy girl"},
            {"name": "Work", "value": "work"},
            {"name": "Linkedin", "value": "linkedin"},
            {"name": "Christmas", "value": "christmas"},
            {"name": "Spice girl", "value": "spice girl"},
            {"name": "Bra", "value": "bra"},
            {"name": "Profile", "value": "profile"},
            {"name": "Resume", "value": "resume"},
            {"name": "Suit", "value": "suit"},
            {"name": "Beautiful lady", "value": "beautiful lady"},
            {"name": "Bikini", "value": "bikini"},
            {"name": "War", "value": "war"},
            {"name": "Business photo", "value": "business photo"},
            {"name": "Watercolor", "value": "watercolor"},
            {"name": "Businessman", "value": "businessman"},
            {"name": "Loli", "value": "loli"},
            {"name": "Actor", "value": "actor"},
            {"name": "Yearbook", "value": "yearbook"},
            {"name": "Vintage", "value": "vintage"},
            {"name": "Angel", "value": "angel"},
            {"name": "Birthday", "value": "birthday"},
        ],
    },
    {
        "name": "Professional Headshot Generator",
        "value": "aiProfessionalHeadshot",
        "subtags": [
            {"name": "Girl", "value": "girl"},
            {"name": "Woman", "value": "woman"},
            {"name": "Man", "value": "man"},
            {"name": "Anime", "value": "anime"},
            {"name": "Fantasy portrait", "value": "fantasy portrait"},
            {"name": "School", "value": "school"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Boy", "value": "boy"},
            {"name": "Business", "value": "business"},
            {"name": "Professional", "value": "professional"},
            {"name": "Headshot", "value": "headshot"},
            {"name": "Sexy girl", "value": "sexy girl"},
            {"name": "Work", "value": "work"},
            {"name": "Linkedin", "value": "linkedin"},
            {"name": "Christmas", "value": "christmas"},
            {"name": "Spice girl", "value": "spice girl"},
            {"name": "Bra", "value": "bra"},
            {"name": "Profile", "value": "profile"},
            {"name": "Resume", "value": "resume"},
            {"name": "Suit", "value": "suit"},
            {"name": "Beautiful lady", "value": "beautiful lady"},
            {"name": "Bikini", "value": "bikini"},
            {"name": "War", "value": "war"},
            {"name": "Business photo", "value": "business photo"},
            {"name": "Watercolor", "value": "watercolor"},
            {"name": "Businessman", "value": "businessman"},
            {"name": "Loli", "value": "loli"},
            {"name": "Actor", "value": "actor"},
            {"name": "Yearbook", "value": "yearbook"},
            {"name": "Vintage", "value": "vintage"},
            {"name": "Angel", "value": "angel"},
            {"name": "Birthday", "value": "birthday"},
        ],
    },
    {
        "name": "AI Architecture Generator",
        "value": "aiArchitecture",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "Building", "value": "building"},
            {"name": "Apartment", "value": "apartment"},
            {"name": "House", "value": "house"},
            {"name": "Exterior", "value": "exterior"},
            {"name": "Villa", "value": "villa"},
            {"name": "Minimalism", "value": "minimalism"},
            {"name": "Modern architecture", "value": "modern architecture"},
            {"name": "Apartment complex", "value": "apartment complex"},
            {"name": "Shed", "value": "shed"},
            {"name": "School", "value": "school"},
            {"name": "Modern house", "value": "modern house"},
            {"name": "Home", "value": "home"},
            {"name": "Brutalist architecture", "value": "brutalist architecture"},
            {"name": "Gothic architecture", "value": "gothic architecture"},
            {"name": "Architectural", "value": "architectural"},
            {"name": "Architectural design", "value": "architectural design"},
            {"name": "Landscape architecture", "value": "landscape architecture"},
            {"name": "Architectural shingles", "value": "architectural shingles"},
            {"name": "Apartment buildings", "value": "apartment buildings"},
            {"name": "Steel buildings", "value": "steel buildings"},
        ],
    },
    {
        "name": "Scenario Changer",
        "value": "aiScenarioChanger",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "3d rendering", "value": "3d rendering"},
            {"name": "Modern architecture", "value": "modern architecture"},
            {"name": "Girl", "value": "girl"},
            {"name": "Interior", "value": "interior"},
            {"name": "Floorplan home", "value": "floorplan home"},
            {"name": "Logo", "value": "logo"},
            {"name": "Woman", "value": "woman"},
            {"name": "Man", "value": "man"},
            {"name": "Anime", "value": "anime"},
            {"name": "Floor plan", "value": "floor plan"},
            {"name": "Landscape plan", "value": "landscape plan"},
            {"name": "Sketch", "value": "sketch"},
            {"name": "Schoolgirl", "value": "schoolgirl"},
            {"name": "Modern house", "value": "modern house"},
            {"name": "Fantasy portrait", "value": "fantasy portrait"},
            {"name": "Professional", "value": "professional"},
            {"name": "School", "value": "school"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Couple", "value": "couple"},
            {"name": "House floorplan", "value": "house floorplan"},
            {"name": "Boy", "value": "boy"},
            {"name": "Plan", "value": "plan"},
            {"name": "House", "value": "house"},
            {"name": "Bedroom", "value": "bedroom"},
            {"name": "Teen", "value": "teen"},
            {"name": "Office", "value": "office"},
            {"name": "Car", "value": "car"},
            {"name": "Business", "value": "business"},
        ],
    },
    {"name": "Panorama Generator", "value": "aiPanorama", "subtags": []},
    {
        "name": "Vector Converter",
        "value": "aiSVG",
        "subtags": [
            {"name": "Architecture", "value": "architecture"},
            {"name": "3d rendering", "value": "3d rendering"},
            {"name": "Modern architecture", "value": "modern architecture"},
            {"name": "Girl", "value": "girl"},
            {"name": "Interior", "value": "interior"},
            {"name": "Floorplan home", "value": "floorplan home"},
            {"name": "Logo", "value": "logo"},
            {"name": "Woman", "value": "woman"},
            {"name": "Man", "value": "man"},
            {"name": "Anime", "value": "anime"},
            {"name": "Floor plan", "value": "floor plan"},
            {"name": "Landscape plan", "value": "landscape plan"},
            {"name": "Sketch", "value": "sketch"},
            {"name": "Schoolgirl", "value": "schoolgirl"},
            {"name": "Modern house", "value": "modern house"},
            {"name": "Fantasy portrait", "value": "fantasy portrait"},
            {"name": "Professional", "value": "professional"},
            {"name": "School", "value": "school"},
            {"name": "Cartoon", "value": "cartoon"},
            {"name": "Kitchen", "value": "kitchen"},
            {"name": "Couple", "value": "couple"},
            {"name": "House floorplan", "value": "house floorplan"},
            {"name": "Boy", "value": "boy"},
            {"name": "Plan", "value": "plan"},
            {"name": "House", "value": "house"},
            {"name": "Bedroom", "value": "bedroom"},
            {"name": "Teen", "value": "teen"},
            {"name": "Office", "value": "office"},
            {"name": "Car", "value": "car"},
            {"name": "Business", "value": "business"},
        ],
    },
]
